services:
  - type: static
    name: venue-allocator-frontend
    staticPublishPath: frontend/dist
    routes:
      - path: /api/*
        destination: https://venue-allocator.onrender.com/api/:path
      - path: /socket.io/*
        destination: https://venue-allocator.onrender.com/socket.io/:path
      - path: /*
        destination: /index.html
